categories = [
    "Toutes les Catégories",
    "--- Véhicules",
    "Voitures",
    "Moto",
    "Véhicules Professionnels",
    "Bateaux",
    "Pièces & Accessoires",
    "--- Immobilier",
    "Location - Appartements",
    "Vente - Appartements",
    "Location - Maisons",
    "Vente - Maisons",
    "Location de vacances",
    "Terrains & Fermes",
    "Commerces & Bureaux",
    "Colocations",
    "Autre Immobilier",
    "--- Multimédia",
    "Téléphones",
    "Informatiques",
    "Jeux vidéo & consoles",
    "Télévisions",
    "Image & son",
    "--- Vêtements et objets",
    "Vêtements",
    "Chaussures",
    "Montres et Bijoux",
    "Bébé",
    "Parfums & Beauté",
    "--- Pour la Maison et Jardin",
    "Meubles & Décoration",
    "Electroménager & Vaisselles",
    "Jardins & Bricolage",
    "--- Loisir",
    "Animaux",
    "Sports & Vélos",
    "Livres & Magazines",
    "Voyages & Séjours",
    "Musique & Instruments",
    "--- Emploi & Services",
    "Offres d'emploi",
    "Demandes d'emploi",
    "Cours & Formation",
    "Services",
    "--- Divers",
    "Matériels PRO & Stocks",
    "Bon plans & DEALS",
    "Affaires & Partenariat",
    "Autre",
]
# villes = [
#    "Toute la Tunisie",
#    "Grand Tunis",
#    "Sahel",
#    "Ariana",
#    "Beja",
#    "Ben arous",
#    "Bizerte",
#    "Gabes",
#    "Gafsa",
#    "Jendouba",
#    "Kairouan",
#    "Kasserine",
#    "Kebili",
#    "Le Kef",
#    "Mahdia",
#    "Manouba",
#    "Medenine",
#    "Monastir",
#    "Nabeul",
#    "Sfax",
#    "Sidi bouzid",
#    "Siliana",
#    "Sousse",
#    "Tataouine",
#    "Tozeur",
#    "Tunis",
#    "Zaghouan"
# ]
categorieId = [
   "a-vendre",
   "vehicule",
   "voiture-neuve-occassion-prix-tayara-a-vendre",
   "motos-vespa-quad-a-vendre",
   "camion-industriel-agricole-a-vendre",
   "bateaux-a-vendre",
   "pieces-accessoires-auto-moto-a-vendre",
   "immobilier",
   "location-appartement",
   "vente-appartement",
   "location-maison",
   "vente-maison",
   "location-de-vacances",
   "terrain",
   "commerces-bureaux-a-vendre-a-louer",
   "colocations",
   "autre-immobilier",
   "multimedia-high-tech-a-vendre",
   "telephone-a-vendre",
   "informatique-a-vendre",
   "jeux-video-et-consoles-a-vendre",
   "television-a-vendre",
   "image-et-son-a-vendre",
   "vetements-objets-a-vendre",
   "vetements",
   "chaussures",
   "montres-bijoux",
   "equipements-bebe-a-vendre",
   "produit-de-beaute-parfum-soin-a-vendre",
   "equipements-maison-a-vendre",
   "meubles-et-decoration-a-vendre",
   "electromenager-vaisselles-a-vendre",
   "vente-materiel-bricolage-jardin",
   "loisir",
   "animaux-a-vendre",
   "sport-et-loisir-a-vendre",
   "film-livre-magazine-a-vendre",
   "voyage-et-sejours",
   "musique-et-instrument-a-vendre",
   "emploi-formation-service",
   "offres-emploi",
   "demandes-emploi",
   "cours-formation",
   "services",
   "autres",
   "materiel-pro-stock-a-vendre",
   "bon-plans-et-big-deals",
   "affaires-et-partenariat",
   "autre"
]
villeId = [
   "tunisie",
   "grand-tunis",
   "sahel",
   "ariana",
   "beja",
   "ben-arous",
   "bizerte",
   "gabes",
   "gafsa",
   "jendouba",
   "kairouan",
   "kasserine",
   "kebili",
   "le-kef",
   "mahdia",
   "manouba",
   "medenine",
   "monastir",
   "nabeul",
   "sfax",
   "sidi-bouzid",
   "siliana",
   "sousse",
   "tataouine",
   "tozeur",
   "tunis",
   "zaghouan"
]
regionId = {
   "ariana": [
      "ariana-ville",
      "ettadhamen",
      "kalaat-el-andalous",
      "la-soukra",
      "mnihla",
      "raoued",
      "sidi-thabet",
      "borj-louzir",
      "chotrana",
      "ennasr",
      "ghazela",
      "jardins-d-el-menzah",
      "manar",
      "menzah"
   ],
   "beja": [
      "amdoun",
      "beja-nord",
      "beja-sud",
      "goubellat",
      "medjez-el-bab",
      "nefza",
      "teboursouk",
      "testour",
      "thibar"
   ],
   "ben-arous": [
      "ben-arous",
      "borj-cedria",
      "boumhel",
      "el-mourouj",
      "ezzahra",
      "fouchana",
      "hammam-chott",
      "hammam-lif",
      "mohamedia",
      "medina-jedida",
      "megrine",
      "mornag",
      "rades"
   ],
   "bizerte": [
      "bizerte-nord",
      "bizerte-sud",
      "djoumime",
      "el-alia",
      "ghar-el-melh",
      "ghezala",
      "mateur",
      "menzel-bourguiba",
      "menzel-jemil",
      "ras-jebel",
      "sejenane",
      "tinja",
      "utique",
      "zarzouna"
   ],
   "gabes": [
      "gabes-medina",
      "gabes-ouest",
      "gabes-sud",
      "ghanouch",
      "el-hamma",
      "matmata",
      "mareth",
      "menzel-el-habib",
      "metouia",
      "nouvelle-matmata"
   ],
   "gafsa": [
      "belkhir",
      "el-guettar",
      "el-ksar",
      "gafsa-nord",
      "gafsa-sud",
      "mdhila",
      "metlaoui",
      "oum-el-araies",
      "redeyef",
      "sidi-aich",
      "sened"
   ],
   "jendouba": [
      "ain-draham",
      "balta-bou-aouane",
      "bou-salem",
      "fernana",
      "ghardimaou",
      "jendouba",
      "jendouba-nord",
      "oued-meliz",
      "tabarka"
   ],
   "kairouan": [
      "bouhajla",
      "chebika",
      "echrarda",
      "el-alaa",
      "el-ouslatia",
      "haffouz",
      "hajeb-el-ayoun",
      "kairouan-nord",
      "kairouan-sud",
      "nasrallah",
      "sbikha"
   ],
   "kasserine": [
      "djedeliane",
      "el-ayoun",
      "ezzouhour-kasserine",
      "feriana",
      "foussana",
      "hassi-ferid",
      "hidra",
      "kasserine-nord",
      "kasserine-sud",
      "majel-bel-abbes",
      "sbeitla",
      "sbiba",
      "thala"
   ],
   "kebili": [
      "douz-nord",
      "douz-sud",
      "faouar",
      "kebili-nord",
      "kebili-sud",
      "souk-lahad"
   ],
   "le-kef": [
      "dahmani",
      "djerissa",
      "el-ksour",
      "sers",
      "kalaat-khasbah",
      "kalaat-snan",
      "kef-est",
      "kef-ouest",
      "nebeur",
      "sakiet-sidi-youssef",
      "tajerouine"
   ],
   "mahdia": [
      "bou-merdes",
      "chebba",
      "chorbane",
      "el-jem",
      "essouassi",
      "hebira",
      "ksour-essef",
      "mahdia",
      "mellouleche",
      "ouled-chamekh",
      "sidi-alouane"
   ],
   "manouba": [
      "borj-el-amri",
      "djedeida",
      "douar-hicher",
      "el-battan",
      "mornaguia",
      "oued-ellil",
      "tebourba",
      "manouba-ville",
      "denden",
      "ksar-said"
   ],
   "medenine": [
      "ben-gardane",
      "beni-khedech",
      "djerba-ajim",
      "djerba-houmt-souk",
      "djerba-midoun",
      "medenine-nord",
      "medenine-sud",
      "sidi-makhloulf",
      "zarzis"
   ],
   "monastir": [
      "bekalta",
      "bembla",
      "beni-hassen",
      "jemmal",
      "ksar-hellal",
      "ksibet-el-mediouni",
      "moknine",
      "monastir",
      "ouerdanine",
      "sahline",
      "sayada-lamta-bou-hajar",
      "teboulba",
      "zeramdine"
   ],
   "nabeul": [
      "beni-khalled",
      "beni-khiar",
      "bou-argoub",
      "dar-chaabane-el-fehri",
      "el-haouaria",
      "el-mida",
      "grombalia",
      "hammam-ghezeze",
      "hammamet",
      "kelibia",
      "korba",
      "menzel-bouzelfa",
      "menzel-temime",
      "nabeul",
      "soliman",
      "takelsa",
      "hammamet-centre",
      "hammamet-nord",
      "hammamet-sud",
      "mrezga"
   ],
   "sfax": [
      "agareb",
      "bir-ali-ben-khalifa",
      "jebiniana",
      "el-amra",
      "el-hencha",
      "ghraiba",
      "kerkennah",
      "mahres",
      "menzel-chaker",
      "sakiet-edda\u00efer",
      "sakiet-ezzit",
      "sfax-ville",
      "skhira",
      "thyna",
      "sfax-medina",
      "route-el-ain",
      "route-el-afrane",
      "route-gremda",
      "route-menzel-chaker",
      "route-matar",
      "route-soukra",
      "route-tunis",
      "route-mehdia",
      "route-teniour"
   ],
   "sidi-bouzid": [
      "bir-el-hafey",
      "cebbala-ouled-asker",
      "jilma",
      "meknassy",
      "menzel-bouzaiane",
      "mezzouna",
      "ouled-haffouz",
      "regueb",
      "sidi-ali-ben-aoun",
      "sidi-bouzid-est",
      "sidi-bouzid-ouest",
      "souk-jedid"
   ],
   "siliana": [
      "bargou",
      "bou-arada",
      "sidi-bou-rouis",
      "el-aroussa",
      "el-krib",
      "rouhia",
      "gaafour",
      "kesra",
      "makthar",
      "siliana-nord",
      "siliana-sud"
   ],
   "sousse": [
      "akouda",
      "bouficha",
      "enfidha",
      "hammam-sousse",
      "hergla",
      "kalaa-kebira",
      "kalaa-sghira",
      "kondar",
      "m-saken",
      "sidi-bou-ali",
      "sidi-el-heni",
      "sousse-jawhara",
      "sousse-medina",
      "sousse-riadh",
      "sousse-sidi-abdelhamid",
      "zaouit-ksibat-thrayett",
      "sahloul",
      "kantaoui"
   ],
   "tataouine": [
      "bir-lahmar",
      "dehiba",
      "ghomrassen",
      "remada",
      "smar",
      "tataouine-nord",
      "tataouine-sud"
   ],
   "tozeur": [
      "degache",
      "hazoua",
      "nefta",
      "tameghza",
      "tozeur"
   ],
   "tunis": [
      "carthage",
      "cite-el-khadra",
      "djebel-jelloud",
      "el-kabaria",
      "el-omrane",
      "el-omrane-superieur",
      "el-ouardia",
      "ettahrir",
      "ezzouhour-tunis",
      "hra\u00efria",
      "la-goulette",
      "la-marsa",
      "le-bardo",
      "le-kram",
      "medina",
      "sejoumi",
      "sidi-el-bechir",
      "sidi-hassine",
      "agba",
      "a\u00efn-zaghouan",
      "centre-urbain-nord",
      "centre-ville-lafayette",
      "cite-olympique",
      "gammarth",
      "jardin-de-carthage",
      "aouina",
      "les-berges-du-lac",
      "mutuelleville",
      "sidi-bou-said",
      "sidi-daoud"
   ],
   "zaghouan": [
      "bir-mchergua",
      "el-fahs",
      "en-nadhour",
      "ez-zeriba",
      "saouaf",
      "zaghouan"
   ]
}